# Generated by Django 3.0.5 on 2020-04-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_photo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
    ]
