# Generated by Django 3.0.5 on 2020-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20200421_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbs/'),
        ),
    ]
