# Generated by Django 3.0.5 on 2020-04-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contest', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commented_type',
        ),
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_object_id', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Comment')),
                ('commented_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
