# Generated by Django 3.0.5 on 2020-05-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnail',
            new_name='thumb_for_gallery',
        ),
    ]
