# Generated by Django 3.0.5 on 2020-05-05 21:53

import contest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contest', '0013_auto_20200504_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_object_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to=contest.models.get_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_for_gallery',
            field=models.FileField(null=True, upload_to=contest.models.get_path),
        ),
        migrations.DeleteModel(
            name='CommentItem',
        ),
    ]
